---
version: '3.3'
services:
  react-web:
    build:
      dockerfile: ./Dockerfile
      context: "./"
    image: web:dev
    ports:
      - "3000:3000"
    stdin_open: true
    volumes:      
      - ./../web:/react-web
      - /react-web/node_modules

